"""add byok fields to user

Revision ID: 73d37bbdf43d
Revises: 362ee7567368
Create Date: 2026-03-20 14:38:20.010750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d37bbdf43d'
down_revision: Union[str, None] = '362ee7567368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gemini_api_key_encrypted', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('byok_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'byok_enabled')
    op.drop_column('users', 'gemini_api_key_encrypted')
    # ### end Alembic commands ###
