"""add_bounding_box_fields_to_chunks

Revision ID: 962463129f99
Revises: 73d37bbdf43d
Create Date: 2026-03-21 10:36:30.502199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962463129f99'
down_revision: Union[str, None] = '73d37bbdf43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('bbox_x1', sa.Float(), nullable=True))
    op.add_column('document_chunks', sa.Column('bbox_y1', sa.Float(), nullable=True))
    op.add_column('document_chunks', sa.Column('bbox_x2', sa.Float(), nullable=True))
    op.add_column('document_chunks', sa.Column('bbox_y2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'bbox_y2')
    op.drop_column('document_chunks', 'bbox_x2')
    op.drop_column('document_chunks', 'bbox_y1')
    op.drop_column('document_chunks', 'bbox_x1')
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###
